import Config

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20
# For development, we disable any cache and enable
# debugging and code reloading.
config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  #
  # Changing this configuration will require mix clean and a full recompile.
  # The watchers configuration can be used to run external
  # watchers to your application. For example, we can use it
  # to bundle .js and .css sources.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

config :plant_watcher, PlantWatcherWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # ## SSL Support
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  #
  # In order to use HTTPS in development, a self-signed
  # certificate can be generated by running the following
  # Mix task:
  #
  #     mix phx.gen.cert
  #
  # Run `mix help phx.gen.cert` for more information.
  #
  # The `http:` config above can be replaced with:
  #
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "5VoboOazabw4SokrOFtBIVFz3a3s7kqPwV+zc6lYl0qHtC6R3fUSRpI+b30Z0Rts",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:plant_watcher, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:plant_watcher, ~w(--watch)]}
  ]

# Reload browser tabs when matching files change.
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
config :plant_watcher, PlantWatcherWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      #     ],
      #
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      # If desired, both `http:` and `https:` keys can be
      # configured to run both http and https servers on
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      # different ports.

      ~r"lib/plant_watcher_web/router\.ex$"E,
      ~r"lib/plant_watcher_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :plant_watcher, dev_routes: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

import_config("dev.secret.exs")
